🧱build : Blue-Green 무중단 배포전략 적용

diff --git a/backend/Jenkinsfile b/backend/Jenkinsfile
--- a/backend/Jenkinsfile
+++ b/backend/Jenkinsfile
@@ -1,15 +1,55 @@
 pipeline {
     agent any
     environment {
-        DOCKERHUB_CREDENTIALS = credentials('docker_hub_token') // Docker Hub 자격 증명 ID
-        DOCKER_REPO = "limnyn/crewin"
-        DOCKER_TAG = "backend" // 태그를 backend로 지정
-        DOCKER_IMAGE = "${DOCKER_REPO}:${DOCKER_TAG}"
-        HOST_CONATINER_PORT = "12380:8080"
-        CONTAINER_NAME = "crewin_springboot_server_blue"
-        CONTAINER_NETWORK = "crewin_network"
+        DOCKERHUB_CREDENTIALS = credentials('docker_hub_token')
+        CREWIN_ENV = credentials('jenkins_crewin_backend.env') //secretfile 가져오기
     }
     stages {
+        stage('Load Environment Variables') {
+            steps {
+                script {
+                    // jenkins_crewin_backend.env 파일 내용을 젠킨스 파일의 환경 변수로 로드
+                    def props = readProperties file: "${CREWIN_ENV}"
+                    env.DOCKER_REPO = props.DOCKER_REPO
+                    env.DOCKER_TAG = props.DOCKER_TAG
+                    env.DOCKER_IMAGE = "${props.DOCKER_REPO}:${props.DOCKER_TAG}"
+                    env.BLUE_PORT = props.BLUE_PORT
+                    env.GREEN_PORT = props.GREEN_PORT
+                    env.CONTAINER_NAME_BLUE = props.CONTAINER_NAME_BLUE
+                    env.CONTAINER_NAME_GREEN = props.CONTAINER_NAME_GREEN
+                    env.CONTAINER_URL = props.CONTAINER_URL
+                    env.NGINX_CONTAINER_NAME = props.NGINX_CONTAINER_NAME
+                    env.NGINX_CONFIG_PATH = props.NGINX_CONFIG_PATH
+                    env.MATTERMOST_CHANNEL_NAME = props.MATTERMOST_CHANNEL_NAME
+                    env.MATTERMOST_WEBHOOK_URL = props.MATTERMOST_WEBHOOK_URL
+                    env.DOCKER_NETWORK = props.DOCKER_NETWORK
+                }
+            }
+        }
+        stage('Notify Build Start') {
+            steps {
+                script {
+                    def Author_ID = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
+                    def Author_Name = sh(script: "git show -s --pretty=%ae", returnStdout: true).trim()
+                    def Commit_Message = sh(script: "git log -1 --pretty=%B", returnStdout: true).trim()
+                    def message = """
+                        #### 빌드 시작 : ${Commit_Message}
+                        **빌드 번호** ${env.JOB_NAME} #${env.BUILD_NUMBER}
+                        **브랜치:** ${env.GIT_BRANCH}
+                        **작성자:** ${Author_ID} (${Author_Name})
+                        **빌드 URL:** [Details](${env.BUILD_URL})
+                    """.stripIndent()
+
+                    mattermostSend(
+                        color: '#439FE0',
+                        message: message,
+                        endpoint: "${env.MATTERMOST_WEBHOOK_URL}",
+                        channel: "${env.MATTERMOST_CHANNEL_NAME}",
+                        icon: 'https://jenkins.io/images/logos/jenkins/jenkins.png'  // Jenkins 로고 URL
+                    )
+                }
+            }
+        }
         stage('Checkout') {
             steps {
                 checkout scm
@@ -24,12 +64,6 @@ pipeline {
                         cp $CONFIG_FILE backend/src/main/resources/application.yml
                     '''
                 }
-//                 withCredentials([file(credentialsId: 'crewin-keystore', variable: 'CONFIG_FILE')]) {
-//                     sh '''
-//                         chmod -R 755 backend/src/main/resources
-//                         cp $CONFIG_FILE backend/src/main/resources/keystore.p12
-//                     '''
-//                 }
             }
         }
         stage('Build & Test') {
@@ -60,7 +94,7 @@ pipeline {
                 }
             }
         }
-        stage('Deploy to Server') {
+        stage('Deploy and Update Nginx') {
             steps {
                 script {
                     sshPublisher(
@@ -70,13 +104,40 @@ pipeline {
                                 transfers: [
                                     sshTransfer(
                                         execCommand: """
-                                            docker pull $DOCKER_IMAGE
-                                            if [ \$(docker ps -q -f name=$CONTAINER_NAME) ]; then
-                                                docker stop $CONTAINER_NAME
-                                                docker rm $CONTAINER_NAME
+                                            docker pull ${env.DOCKER_IMAGE}
+                                            CURRENT_CONTAINER=\$(docker ps -q --filter name=${env.CONTAINER_NAME_BLUE})
+                                            if [ -n "$CURRENT_CONTAINER" ]; then
+                                                NEW_PORT=${env.GREEN_PORT}
+                                                NEW_NAME=${env.CONTAINER_NAME_GREEN}
+                                                OLD_NAME=${env.CONTAINER_NAME_BLUE}
+                                                CURRENT_PORT=${env.BLUE_PORT}
+                                            else
+                                                NEW_PORT=${env.BLUE_PORT}
+                                                NEW_NAME=${env.CONTAINER_NAME_BLUE}
+                                                OLD_NAME=${env.CONTAINER_NAME_GREEN}
+                                                CURRENT_PORT=${env.GREEN_PORT}
                                             fi
-                                            docker run -d --name $CONTAINER_NAME --network $CONTAINER_NETWORK -p $HOST_CONATINER_PORT $DOCKER_IMAGE
-
+                                            docker run -d --name $NEW_NAME --network ${env.DOCKER_NETWORK} -p $NEW_PORT:8080 ${env.DOCKER_IMAGE}
+                                            sleep 10
+                                            if curl -sf -m 5 http://localhost:$NEW_PORT/health > /dev/null; then
+                                                # Update Nginx config
+                                                sed -i "s/server ${env.CONTAINER_URL}:$NEW_PORT down;/server ${env.CONTAINER_URL}:$NEW_PORT;/" ${env.NGINX_CONFIG_PATH}
+                                                sed -i "s/server ${env.CONTAINER_URL}:$CURRENT_PORT;/server ${env.CONTAINER_URL}:$CURRENT_PORT down;/" ${env.NGINX_CONFIG_PATH}
+                                                # Restart Nginx container
+                                                docker restart ${env.NGINX_CONTAINER_NAME}
+                                                # Stop and remove old container
+                                                docker stop $OLD_NAME
+                                                docker rm $OLD_NAME
+                                                echo "Switched to new version on port $NEW_PORT and updated Nginx"
+                                                # success
+                                                exit 0
+                                            else
+                                                docker stop $NEW_NAME
+                                                docker rm $NEW_NAME
+                                                echo "Deployment failed, keeping old version"
+                                                # failure return
+                                                exit 1
+                                            fi
                                         """
                                     )
                                 ]
@@ -89,13 +150,31 @@ pipeline {
     }
     post {
         always {
-            echo "파이프라인 실행이 완료되었습니다."
-        }
-        success {
-            echo "파이프라인이 성공적으로 실행되었습니다."
-        }
-        failure {
-            echo "파이프라인 실행 중 오류가 발생했습니다."
+            script {
+                def Author_ID = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
+                def Author_Name = sh(script: "git show -s --pretty=%ae", returnStdout: true).trim()
+                def Commit_Message = sh(script: "git log -1 --pretty=%B", returnStdout: true).trim()
+                def Build_Status = currentBuild.result ?: 'SUCCESS'
+                def Status_Color = Build_Status == 'SUCCESS' ? 'good' : (Build_Status == 'UNSTABLE' ? 'warning' : 'danger')
+                def Status_Text = Build_Status == 'SUCCESS' ? '빌드 성공' : (Build_Status == 'UNSTABLE' ? '빌드 불안정' : '빌드 실패')
+
+                def message = """
+                    #### ${Status_Text} : ${Commit_Message}
+                    **빌드 번호** ${env.JOB_NAME} #${env.BUILD_NUMBER}
+                    **브랜치:** ${env.GIT_BRANCH}
+                    **작성자:** ${Author_ID} (${Author_Name})
+                    **빌드 URL:** [Details](${env.BUILD_URL})
+                """.stripIndent()
+
+
+                mattermostSend(
+                    color: Status_Color,
+                    message: message,
+                    endpoint: "${env.MATTERMOST_WEBHOOK_URL}",
+                    channel: "${env.MATTERMOST_CHANNEL_NAME}",
+                    icon: 'https://jenkins.io/images/logos/jenkins/jenkins.png'  // Jenkins 로고 URL
+                )
+            }
         }
     }
 }
